name: gtfs_db
description: Transit DB made out of GTFS file.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=2.11.0-0.1.pre"

flutter:
  assets:
    - assets/sqlite/kaunas.sqlite

dependencies:
  flutter:
    sdk: flutter

  archive: ^3.3.1
  csv: ^5.0.1
  drift: ^1.7.1
  http: ^0.13.5
  path: ^1.8.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.0
  build_test: ^2.1.0
  drift_dev: ^1.7.1
